# Final Project by Denise Godinez (00001614313), Jack Mulvihill (00001623740), and Fareen Samad (00001663164)

## Abstract

## Imported Libraries

In [1]:
import glob
import pandas as pd

## Data Extraction

In [2]:
# Preview one of the data sources
ex = pd.read_json('ids_4.json', lines=True)

# Display the columns
print(ex.columns)

display(ex.head())

Index([' Destination Port', ' Flow Duration', ' Total Fwd Packets',
       ' Total Backward Packets', 'Total Length of Fwd Packets',
       ' Total Length of Bwd Packets', ' Fwd Packet Length Max',
       ' Fwd Packet Length Min', ' Fwd Packet Length Mean',
       ' Fwd Packet Length Std', 'Bwd Packet Length Max',
       ' Bwd Packet Length Min', ' Bwd Packet Length Mean',
       ' Bwd Packet Length Std', 'Flow Bytes/s', ' Flow Packets/s',
       ' Flow IAT Mean', ' Flow IAT Std', ' Flow IAT Max', ' Flow IAT Min',
       'Fwd IAT Total', ' Fwd IAT Mean', ' Fwd IAT Std', ' Fwd IAT Max',
       ' Fwd IAT Min', 'Bwd IAT Total', ' Bwd IAT Mean', ' Bwd IAT Std',
       ' Bwd IAT Max', ' Bwd IAT Min', 'Fwd PSH Flags', ' Bwd PSH Flags',
       ' Fwd URG Flags', ' Bwd URG Flags', ' Fwd Header Length',
       ' Bwd Header Length', 'Fwd Packets/s', ' Bwd Packets/s',
       ' Min Packet Length', ' Max Packet Length', ' Packet Length Mean',
       ' Packet Length Std', ' Packet Length Variance', 'FIN Flag Count',
       ' SYN Flag Count', ' RST Flag Count', ' PSH Flag Count',
       ' ACK Flag Count', ' URG Flag Count', ' CWE Flag Count',
       ' ECE Flag Count', ' Down/Up Ratio', ' Average Packet Size',
       ' Avg Fwd Segment Size', ' Avg Bwd Segment Size',
       ' Fwd Header Length.1', 'Fwd Avg Bytes/Bulk', ' Fwd Avg Packets/Bulk',
       ' Fwd Avg Bulk Rate', ' Bwd Avg Bytes/Bulk', ' Bwd Avg Packets/Bulk',
       'Bwd Avg Bulk Rate', 'Subflow Fwd Packets', ' Subflow Fwd Bytes',
       ' Subflow Bwd Packets', ' Subflow Bwd Bytes', 'Init_Win_bytes_forward',
       ' Init_Win_bytes_backward', ' act_data_pkt_fwd',
       ' min_seg_size_forward', 'Active Mean', ' Active Std', ' Active Max',
       ' Active Min', 'Idle Mean', ' Idle Std', ' Idle Max', ' Idle Min',
       ' Label'],
      dtype='str')

,Destination Port,Flow Duration,Total Fwd Packets,Total Backward Packets,Total Length of Fwd Packets,Total Length of Bwd Packets,Fwd Packet Length Max,Fwd Packet Length Min,Fwd Packet Length Mean,Fwd Packet Length Std,...,min_seg_size_forward,Active Mean,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,Label
0,80,27887,2,0,12,0,6,6,6.0,0.0,...,20,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN
1,53,181,2,2,74,154,37,37,37.0,0.0,...,44,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN
2,80,115,2,0,12,0,6,6,6.0,0.0,...,20,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN
3,80,13,1,1,6,6,6,6,6.0,0.0,...,20,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN
4,56529,50,1,1,0,0,0,0,0.0,0.0,...,32,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN

In [3]:
"""This functions combines all the csv, json, and parquet files into a dataframe

    Args:
        None: The function reads all csv, json, and parquet files in the working directory
        
    Returns:
        data (pd.DataFrame): All data sources combined in a single dataframe
    """
def extract() -> pd.DataFrame:
    
    # Create a new dataframe to hold all the data
    # Column names chosen based on what was returned from .columns
    data = pd.DataFrame(columns=[' Destination Port', ' Flow Duration', ' Total Fwd Packets',
                                 ' Total Backward Packets', 'Total Length of Fwd Packets',
                                 ' Total Length of Bwd Packets', ' Fwd Packet Length Max',
                                 ' Fwd Packet Length Min', ' Fwd Packet Length Mean',
                                 ' Fwd Packet Length Std', 'Bwd Packet Length Max',
                                 ' Bwd Packet Length Min', ' Bwd Packet Length Mean',
                                 ' Bwd Packet Length Std', 'Flow Bytes/s', ' Flow Packets/s',
                                 ' Flow IAT Mean', ' Flow IAT Std', ' Flow IAT Max', ' Flow IAT Min',
                                 'Fwd IAT Total', ' Fwd IAT Mean', ' Fwd IAT Std', ' Fwd IAT Max',
                                 ' Fwd IAT Min', 'Bwd IAT Total', ' Bwd IAT Mean', ' Bwd IAT Std',
                                 ' Bwd IAT Max', ' Bwd IAT Min', 'Fwd PSH Flags', ' Bwd PSH Flags',
                                 ' Fwd URG Flags', ' Bwd URG Flags', ' Fwd Header Length',
                                 ' Bwd Header Length', 'Fwd Packets/s', ' Bwd Packets/s',
                                 ' Min Packet Length', ' Max Packet Length', ' Packet Length Mean',
                                 ' Packet Length Std', ' Packet Length Variance', 'FIN Flag Count',
                                 ' SYN Flag Count', ' RST Flag Count', ' PSH Flag Count',
                                 ' ACK Flag Count', ' URG Flag Count', ' CWE Flag Count',
                                 ' ECE Flag Count', ' Down/Up Ratio', ' Average Packet Size',
                                 ' Avg Fwd Segment Size', ' Avg Bwd Segment Size',
                                 ' Fwd Header Length.1', 'Fwd Avg Bytes/Bulk', ' Fwd Avg Packets/Bulk',
                                 ' Fwd Avg Bulk Rate', ' Bwd Avg Bytes/Bulk', ' Bwd Avg Packets/Bulk',
                                 'Bwd Avg Bulk Rate', 'Subflow Fwd Packets', ' Subflow Fwd Bytes',
                                 ' Subflow Bwd Packets', ' Subflow Bwd Bytes', 'Init_Win_bytes_forward',
                                 ' Init_Win_bytes_backward', ' act_data_pkt_fwd',
                                 ' min_seg_size_forward', 'Active Mean', ' Active Std', ' Active Max',
                                 ' Active Min', 'Idle Mean', ' Idle Std', ' Idle Max', ' Idle Min',' Label'])
    
    # Load the csv files
    for csvfile in glob.glob('*.csv'):
        
        # Load current csv into the temp dataframe
        temp = pd.read_csv(csvfile)
        
        # Combine the loaded csv files into data
        data = pd.concat([data, temp], ignore_index=True)
    
    # Load the json files
    for jsonfile in glob.glob('*.json'):
        
        # Load current json into the temp dataframe
        temp = pd.read_json(jsonfile, lines=True)
        
        # Combine the loaded json files into data
        data = pd.concat([data, temp], ignore_index=True)
    
    # Load the parquet files
    for parquetfile in glob.glob('*.parquet'):
        
        # Load the current parquet file into the temp dataframe
        temp = pd.read_parquet(parquetfile)
        
        # Combine the loaded parquet files into data
        data = pd.concat([data, temp], ignore_index=True)
    
    # Return the newly extracted data
    return data

Because all of these data sources share the same attributes, the best approach is to combine all the data from all the files into one combined DataFrame for easy analysis.

In [ ]:
# Extract the data into a dataframe data
data = extract()

# Display all columns
pd.set_option('display.max_columns', None)
display(data.head())

,Destination Port,Flow Duration,Total Fwd Packets,Total Backward Packets,Total Length of Fwd Packets,Total Length of Bwd Packets,Fwd Packet Length Max,Fwd Packet Length Min,Fwd Packet Length Mean,Fwd Packet Length Std,Bwd Packet Length Max,Bwd Packet Length Min,Bwd Packet Length Mean,Bwd Packet Length Std,Flow Bytes/s,Flow Packets/s,Flow IAT Mean,Flow IAT Std,Flow IAT Max,Flow IAT Min,Fwd IAT Total,Fwd IAT Mean,Fwd IAT Std,Fwd IAT Max,Fwd IAT Min,Bwd IAT Total,Bwd IAT Mean,Bwd IAT Std,Bwd IAT Max,Bwd IAT Min,Fwd PSH Flags,Bwd PSH Flags,Fwd URG Flags,Bwd URG Flags,Fwd Header Length,Bwd Header Length,Fwd Packets/s,Bwd Packets/s,Min Packet Length,Max Packet Length,Packet Length Mean,Packet Length Std,Packet Length Variance,FIN Flag Count,SYN Flag Count,RST Flag Count,PSH Flag Count,ACK Flag Count,URG Flag Count,CWE Flag Count,ECE Flag Count,Down/Up Ratio,Average Packet Size,Avg Fwd Segment Size,Avg Bwd Segment Size,Fwd Header Length.1,Fwd Avg Bytes/Bulk,Fwd Avg Packets/Bulk,Fwd Avg Bulk Rate,Bwd Avg Bytes/Bulk,Bwd Avg Packets/Bulk,Bwd Avg Bulk Rate,Subflow Fwd Packets,Subflow Fwd Bytes,Subflow Bwd Packets,Subflow Bwd Bytes,Init_Win_bytes_forward,Init_Win_bytes_backward,act_data_pkt_fwd,min_seg_size_forward,Active Mean,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,Label
0,53,61205,4,2,136,428,34,34,34.0,0.0,214,214,214.0,0.0,9214.93342,98.031207,12241.0,16867.17138,33318,3,33324,11108.0,19234.42422,33318,3,4,4.0,0.0,4,4,0,0,0,0,128,40,65.354138,32.677069,34,214,85.428571,87.831007,7714.285714,0,0,0,0,0,0,0,0,0,99.666667,34.0,214.0,128,0,0,0,0,0,0,4,136,2,428,-1,-1,3,32,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN
1,53,222,2,2,90,172,45,45,45.0,0.0,86,86,86.0,0.0,1180180.18,18018.01802,74.0,86.0,170,4,48,48.0,0.0,48,48,4,4.0,0.0,4,4,0,0,0,0,40,40,9009.009009,9009.009009,45,86,61.4,22.456625,504.3,0,0,0,0,0,0,0,0,1,76.75,45.0,86.0,40,0,0,0,0,0,0,2,90,2,172,-1,-1,1,20,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN
2,53,23759,2,2,70,126,35,35,35.0,0.0,63,63,63.0,0.0,8249.505451,168.357254,7919.666667,13711.20288,23752,3,4,4.0,0.0,4,4,3,3.0,0.0,3,3,0,0,0,0,64,40,84.178627,84.178627,35,63,46.2,15.336232,235.2,0,0,0,0,0,0,0,0,1,57.75,35.0,63.0,64,0,0,0,0,0,0,2,70,2,126,-1,-1,1,32,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN
3,80,401,2,0,12,0,6,6,6.0,0.0,0,0,0.0,0.0,29925.18703,4987.531172,401.0,0.0,401,401,401,401.0,0.0,401,401,0,0.0,0.0,0,0,0,0,0,0,40,0,4987.531172,0.0,6,6,6.0,0.0,0.0,0,0,0,0,1,0,0,0,0,9.0,6.0,0.0,40,0,0,0,0,0,0,2,12,0,0,253,-1,1,20,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN
4,57406,4,2,0,12,0,6,6,6.0,0.0,0,0,0.0,0.0,3000000.0,500000.0,4.0,0.0,4,4,4,4.0,0.0,4,4,0,0.0,0.0,0,0,0,0,0,0,40,0,500000.0,0.0,6,6,6.0,0.0,0.0,0,0,0,0,1,0,0,0,0,9.0,6.0,0.0,40,0,0,0,0,0,0,2,12,0,0,362,-1,1,20,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN

## Data Transformation

In [7]:
# Display the data types of each attribute in the newly created combined DataFrame
print(data.dtypes)

 Destination Port              object
 Flow Duration                 object
 Total Fwd Packets             object
 Total Backward Packets        object
Total Length of Fwd Packets    object
                                ...
Idle Mean                      object
 Idle Std                      object
 Idle Max                      object
 Idle Min                      object
 Label                         object
Length: 79, dtype: object

All of these data types seem to be object. So, convert them as necessary based on the information provided when displaying data.

In [11]:
"""This function renames the columns, converts the data types as appropriate, and removes duplicates
    Args:
        data (pd.DataFrame): dataframe BEFORE transformations

    Returns:
        data (pd.DataFrame): dataframe AFTER transformations
    """
def transform(data: pd.DataFrame) -> pd.DataFrame:
    
    # Rename the columns to make them easier to work with
    # Convert all to lower case
    # Remove extra whitespace
    # Replace necessary whitespace with underscores
    data.rename(columns={' Destination Port': 'destination_port', 
                         ' Flow Duration': 'flow_duration', 
                         ' Total Fwd Packets': 'total_fwd_packets',
                         ' Total Backward Packets': 'total_bwd_packets', 
                         'Total Length of Fwd Packets': 'total_len_fwd_packets',
                         ' Total Length of Bwd Packets': 'total_len_bwd_packets', 
                         ' Fwd Packet Length Max': 'fwd_packet_len_max',
                         ' Fwd Packet Length Min': 'fwd_packet_len_min', 
                         ' Fwd Packet Length Mean': 'fwd_packet_len_mean',
                         ' Fwd Packet Length Std': 'fwd_packet_len_std', 
                         'Bwd Packet Length Max': 'bwd_packet_len_max',
                         ' Bwd Packet Length Min': 'bwd_packet_len_min',
                         ' Bwd Packet Length Mean': 'bwd_packet_len_mean',
                         ' Bwd Packet Length Std': 'bwd_packet_len_std',
                         'Flow Bytes/s': 'flow_bytes',
                         ' Flow Packets/s': 'flow_packets',
                         ' Flow IAT Mean': 'flow_iat_mean', 
                         ' Flow IAT Std': 'flow_iat_std', 
                         ' Flow IAT Max': 'flow_iat_max',
                         ' Flow IAT Min': 'flow_iat_min',
                         'Fwd IAT Total': 'fwd_iat_total', 
                         ' Fwd IAT Mean': 'fwd_iat_mean', 
                         ' Fwd IAT Std': 'fwd_iat_std', 
                         ' Fwd IAT Max': 'fwd_iat_max',
                         ' Fwd IAT Min': 'fwd_iat_min', 
                         'Bwd IAT Total': 'bwd_iat_total', 
                         ' Bwd IAT Mean': 'bwd_iat_mean', 
                         ' Bwd IAT Std': 'bwd_iat_std',
                         ' Bwd IAT Max': 'bwd_iat_max', 
                         ' Bwd IAT Min': 'bwd_iat_min', 
                         'Fwd PSH Flags': 'fwd_psh_flags', 
                         ' Bwd PSH Flags': 'bwd_psh_flags',
                         ' Fwd URG Flags': 'fwd_urg_flags', 
                         ' Bwd URG Flags': 'bwd_urg_flags', 
                         ' Fwd Header Length': 'fwd_header_length',
                         ' Bwd Header Length': 'bwd_header_length', 
                         'Fwd Packets/s': 'fwd_packets_per_sec', 
                         ' Bwd Packets/s': 'bwd_packets_per_sec',
                         ' Min Packet Length': 'min_packet_len', 
                         ' Max Packet Length': 'max_packet_len',
                         ' Packet Length Mean': 'packet_len_mean',
                         ' Packet Length Std': 'packet_len_std', 
                         ' Packet Length Variance': 'packet_len_variance', 
                         'FIN Flag Count': 'fin_flag_count',
                         ' SYN Flag Count': 'syn_flag_count', 
                         ' RST Flag Count': 'rst_flag_count', 
                         ' PSH Flag Count': 'psh_flag_count',
                         ' ACK Flag Count': 'ack_flag_count', 
                         ' URG Flag Count': 'urg_flag_count', 
                         ' CWE Flag Count': 'cwe_flag_count',
                         ' ECE Flag Count': 'ece_flag_count', 
                         ' Down/Up Ratio': 'down_up_ratio', 
                         ' Average Packet Size': 'avg_packet_size',
                         ' Avg Fwd Segment Size': 'avg_fwd_segment_size', 
                         ' Avg Bwd Segment Size': 'avg_bwd_segment_size',
                         ' Fwd Header Length.1': 'fwd_header_length_1', 
                         'Fwd Avg Bytes/Bulk': 'fwd_avg_bytes_bulk', 
                         ' Fwd Avg Packets/Bulk': 'fwd_avg_packets_bulk',
                         ' Fwd Avg Bulk Rate': 'fwd_avg_bulk_rate', 
                         ' Bwd Avg Bytes/Bulk': 'bwd_avg_bytes_bulk', 
                         ' Bwd Avg Packets/Bulk': 'bwd_avg_packets_bulk',
                         'Bwd Avg Bulk Rate': 'bwd_avg_bulk_rate', 
                         'Subflow Fwd Packets': 'subflow_fwd_packets', 
                         ' Subflow Fwd Bytes': 'subflow_fwd_bytes',
                         ' Subflow Bwd Packets': 'subflow_bwd_packets', 
                         ' Subflow Bwd Bytes': 'subflow_bwd_bytes',
                         'Init_Win_bytes_forward': 'init_win_bytes_forward',
                         ' Init_Win_bytes_backward': 'init_win_bytes_backward', 
                         ' act_data_pkt_fwd': 'act_data_pkt_fwd',
                         ' min_seg_size_forward': 'min_seg_size_forward', 
                         'Active Mean': 'active_mean', 
                         ' Active Std': 'active_std', 
                         ' Active Max': 'active_max',
                         ' Active Min': 'active_min', 
                         'Idle Mean': 'idle_mean', 
                         ' Idle Std': 'idle_std', 
                         ' Idle Max': 'idle_max', 
                         ' Idle Min': 'idle_min',
                         ' Label': 'label'}, inplace=True)
    
    # Remove the duplicate columns, this seemed to be the only one
    data = data.drop('fwd_header_length_1', axis=1)
    
    # Convert the data types as appropriate based on the head of the dataframe
    data.destination_port = data.destination_port.astype('int64')
    data.flow_duration = data.flow_duration.astype('int64')
    data.total_fwd_packets = data.total_fwd_packets.astype('int64')
    data.total_bwd_packets = data.total_bwd_packets.astype('int64')
    data.total_len_fwd_packets = data.total_len_fwd_packets.astype('int64')
    data.total_len_bwd_packets = data.total_len_bwd_packets.astype('int64')
    data.fwd_packet_len_max = data.fwd_packet_len_max.astype('int64')
    data.fwd_packet_len_min = data.fwd_packet_len_min.astype('int64')
    data.fwd_packet_len_mean = data.fwd_packet_len_mean.astype('float64')
    data.fwd_packet_len_std = data.fwd_packet_len_std.astype('float64')
    data.bwd_packet_len_max = data.bwd_packet_len_max.astype('int64')
    data.bwd_packet_len_min = data.bwd_packet_len_min.astype('int64')
    data.bwd_packet_len_mean = data.bwd_packet_len_mean.astype('float64')
    data.bwd_packet_len_std = data.bwd_packet_len_std.astype('float64')
    data.flow_bytes = data.flow_bytes.astype('float64')
    data.flow_packets = data.flow_packets.astype('float64')
    data.flow_iat_mean = data.flow_iat_mean.astype('float64')
    data.flow_iat_std = data.flow_iat_std.astype('float64')
    data.flow_iat_max = data.flow_iat_max.astype('float64')
    data.flow_iat_min = data.flow_iat_min.astype('float64')
    data.fwd_iat_total = data.fwd_iat_total.astype('float64')
    data.fwd_iat_mean = data.fwd_iat_mean.astype('float64')
    data.fwd_iat_std = data.fwd_iat_std.astype('float64')
    data.fwd_iat_max = data.fwd_iat_max.astype('float64')
    data.fwd_iat_min = data.fwd_iat_min.astype('float64')
    data.bwd_iat_total = data.bwd_iat_total.astype('float64')
    data.bwd_iat_mean = data.bwd_iat_mean.astype('float64')
    data.bwd_iat_std = data.bwd_iat_std.astype('float64')
    data.bwd_iat_max = data.bwd_iat_max.astype('float64')
    data.bwd_iat_min = data.bwd_iat_min.astype('float64')
    data.fwd_psh_flags = data.fwd_psh_flags.astype('int64')
    data.bwd_psh_flags = data.bwd_psh_flags.astype('int64')
    data.fwd_urg_flags = data.fwd_urg_flags.astype('int64')
    data.bwd_urg_flags = data.bwd_urg_flags.astype('int64')
    data.fwd_header_length = data.fwd_header_length.astype('int64')
    data.bwd_header_length = data.bwd_header_length.astype('int64')
    data.fwd_packets_per_sec = data.fwd_packets_per_sec.astype('float64')
    data.bwd_packets_per_sec = data.bwd_packets_per_sec.astype('float64')
    data.min_packet_len = data.min_packet_len.astype('int64')
    data.max_packet_len = data.max_packet_len.astype('int64')
    data.packet_len_mean = data.packet_len_mean.astype('float64')
    data.packet_len_std = data.packet_len_std.astype('float64')
    data.packet_len_variance = data.packet_len_variance.astype('float64')
    data.fin_flag_count = data.fin_flag_count.astype('int64')
    data.syn_flag_count = data.syn_flag_count.astype('int64')
    data.rst_flag_count = data.rst_flag_count.astype('int64')
    data.psh_flag_count = data.psh_flag_count.astype('int64')
    data.ack_flag_count = data.ack_flag_count.astype('int64')
    data.urg_flag_count = data.urg_flag_count.astype('int64')
    data.cwe_flag_count = data.cwe_flag_count.astype('int64')
    data.ece_flag_count = data.ece_flag_count.astype('int64')
    data.down_up_ratio = data.down_up_ratio.astype('float64')
    data.avg_packet_size = data.avg_packet_size.astype('float64')
    data.avg_fwd_segment_size = data.avg_fwd_segment_size.astype('float64')
    data.avg_bwd_segment_size = data.avg_bwd_segment_size.astype('float64')
    data.fwd_avg_bytes_bulk = data.fwd_avg_bytes_bulk.astype('float64')
    data.fwd_avg_packets_bulk = data.fwd_avg_packets_bulk.astype('float64')
    data.fwd_avg_bulk_rate = data.fwd_avg_bulk_rate.astype('float64')
    data.bwd_avg_bytes_bulk = data.bwd_avg_bytes_bulk.astype('float64')
    data.bwd_avg_packets_bulk = data.bwd_avg_packets_bulk.astype('float64')
    data.bwd_avg_bulk_rate = data.bwd_avg_bulk_rate.astype('float64')
    data.subflow_fwd_packets = data.subflow_fwd_packets.astype('int64')
    data.subflow_fwd_bytes = data.subflow_fwd_bytes.astype('int64')
    data.subflow_bwd_packets = data.subflow_bwd_packets.astype('int64')
    data.subflow_bwd_bytes = data.subflow_bwd_bytes.astype('int64')
    data.init_win_bytes_forward = data.init_win_bytes_forward.astype('int64')
    data.init_win_bytes_backward = data.init_win_bytes_backward.astype('int64')
    data.act_data_pkt_fwd = data.act_data_pkt_fwd.astype('int64')
    data.min_seg_size_forward = data.min_seg_size_forward.astype('int64')
    data.active_mean = data.active_mean.astype('float64')
    data.active_std = data.active_std.astype('float64')
    data.active_max = data.active_max.astype('float64')
    data.active_min = data.active_min.astype('float64')
    data.idle_mean = data.idle_mean.astype('float64')
    data.idle_std = data.idle_std.astype('float64')
    data.idle_max = data.idle_max.astype('float64')
    data.idle_min = data.idle_min.astype('float64')
    data.label = data.label.astype('string')
    
    # Return the newly transformed data
    return data

In [12]:
data = transform(data)
display(data.head())

,destination_port,flow_duration,total_fwd_packets,total_bwd_packets,total_len_fwd_packets,total_len_bwd_packets,fwd_packet_len_max,fwd_packet_len_min,fwd_packet_len_mean,fwd_packet_len_std,bwd_packet_len_max,bwd_packet_len_min,bwd_packet_len_mean,bwd_packet_len_std,flow_bytes,flow_packets,flow_iat_mean,flow_iat_std,flow_iat_max,flow_iat_min,fwd_iat_total,fwd_iat_mean,fwd_iat_std,fwd_iat_max,fwd_iat_min,bwd_iat_total,bwd_iat_mean,bwd_iat_std,bwd_iat_max,bwd_iat_min,fwd_psh_flags,bwd_psh_flags,fwd_urg_flags,bwd_urg_flags,fwd_header_length,bwd_header_length,fwd_packets_per_sec,bwd_packets_per_sec,min_packet_len,max_packet_len,packet_len_mean,packet_len_std,packet_len_variance,fin_flag_count,syn_flag_count,rst_flag_count,psh_flag_count,ack_flag_count,urg_flag_count,cwe_flag_count,ece_flag_count,down_up_ratio,avg_packet_size,avg_fwd_segment_size,avg_bwd_segment_size,fwd_avg_bytes_bulk,fwd_avg_packets_bulk,fwd_avg_bulk_rate,bwd_avg_bytes_bulk,bwd_avg_packets_bulk,bwd_avg_bulk_rate,subflow_fwd_packets,subflow_fwd_bytes,subflow_bwd_packets,subflow_bwd_bytes,init_win_bytes_forward,init_win_bytes_backward,act_data_pkt_fwd,min_seg_size_forward,active_mean,active_std,active_max,active_min,idle_mean,idle_std,idle_max,idle_min,label
0,53,61205,4,2,136,428,34,34,34.0,0.0,214,214,214.0,0.0,9.214933e+03,98.031207,12241.000000,16867.17138,33318.0,3.0,33324.0,11108.0,19234.42422,33318.0,3.0,4.0,4.0,0.0,4.0,4.0,0,0,0,0,128,40,65.354138,32.677069,34,214,85.428571,87.831007,7714.285714,0,0,0,0,0,0,0,0,0.0,99.666667,34.0,214.0,0.0,0.0,0.0,0.0,0.0,0.0,4,136,2,428,-1,-1,3,32,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,BENIGN
1,53,222,2,2,90,172,45,45,45.0,0.0,86,86,86.0,0.0,1.180180e+06,18018.018020,74.000000,86.00000,170.0,4.0,48.0,48.0,0.00000,48.0,48.0,4.0,4.0,0.0,4.0,4.0,0,0,0,0,40,40,9009.009009,9009.009009,45,86,61.400000,22.456625,504.300000,0,0,0,0,0,0,0,0,1.0,76.750000,45.0,86.0,0.0,0.0,0.0,0.0,0.0,0.0,2,90,2,172,-1,-1,1,20,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,BENIGN
2,53,23759,2,2,70,126,35,35,35.0,0.0,63,63,63.0,0.0,8.249505e+03,168.357254,7919.666667,13711.20288,23752.0,3.0,4.0,4.0,0.00000,4.0,4.0,3.0,3.0,0.0,3.0,3.0,0,0,0,0,64,40,84.178627,84.178627,35,63,46.200000,15.336232,235.200000,0,0,0,0,0,0,0,0,1.0,57.750000,35.0,63.0,0.0,0.0,0.0,0.0,0.0,0.0,2,70,2,126,-1,-1,1,32,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,BENIGN
3,80,401,2,0,12,0,6,6,6.0,0.0,0,0,0.0,0.0,2.992519e+04,4987.531172,401.000000,0.00000,401.0,401.0,401.0,401.0,0.00000,401.0,401.0,0.0,0.0,0.0,0.0,0.0,0,0,0,0,40,0,4987.531172,0.000000,6,6,6.000000,0.000000,0.000000,0,0,0,0,1,0,0,0,0.0,9.000000,6.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2,12,0,0,253,-1,1,20,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,BENIGN
4,57406,4,2,0,12,0,6,6,6.0,0.0,0,0,0.0,0.0,3.000000e+06,500000.000000,4.000000,0.00000,4.0,4.0,4.0,4.0,0.00000,4.0,4.0,0.0,0.0,0.0,0.0,0.0,0,0,0,0,40,0,500000.000000,0.000000,6,6,6.000000,0.000000,0.000000,0,0,0,0,1,0,0,0,0.0,9.000000,6.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2,12,0,0,362,-1,1,20,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,BENIGN

The naming of the columns was inconsistent and contained a lot of unnecessary whitespace, which made it confusing for the users. So, the main goal of transformation was to convert all of the feature names into a standardized format to make working with them easier down the line. In doing so, a duplicate column was identified and deleted from the dataset. The other major issue that needed to be addressed was that all of the data types were of type "object." Based on what was provided when previewing the data, converted all of the data types as appropriate. This included changing the counts and numbers to integers, statistical data to floats, and labels to strings.

## Data Loading and Storage

In [14]:
"""This function loads the argument dataframe data into the csv file identified by filename

    Args:
        data (pd.DataFrame): transformed dataframe
        filename (str): the csv
    """
def loadcsv(data: pd.DataFrame, filename: str) -> None:
    
    # Use .to_csv to convert the dataframe into a CSV
    # use an f-string to write the filename as the string parameter, do not index
    data.to_csv(f'{filename}', index=False)

In [ ]:
# Create the CSV file with the transformed data
loadcsv(data, 'transformed_data.csv')

Loading the transformed data into a CSV file seems like the most logical choice here given that no use of SQL will be necessary in the foreseeable future.

## Data Reading

## Data Analysis

## Data Preprocessing

## Feature Engineering

## Processed Data Loading

## Model Selection and Training

## Model Evaluation